struct KotlinModuleStubPrinter {
  let skippedFunctions: [KotlinSkippedFunction]

  func printModule(
    _ printer: inout CodePrinter,
    packageName: String,
    moduleName: String,
    functions: [KotlinStubFunction]
  ) {
    printHeader(&printer, moduleName: moduleName)
    printPackage(&printer, packageName: packageName)
    printFunctionStubs(&printer, functions: functions)
    printSkippedDeclarations(&printer)
  }

  private func printHeader(_ printer: inout CodePrinter, moduleName: String) {
    printer.print("// Generated by jextract-swift")
    printer.print("// Swift module: \(moduleName)")
    printer.print("")
  }

  private func printPackage(_ printer: inout CodePrinter, packageName: String) {
    guard !packageName.isEmpty else {
      return
    }

    printer.print("package \(packageName)")
    printer.print("")
  }

  private func printFunctionStubs(
    _ printer: inout CodePrinter,
    functions: [KotlinStubFunction]
  ) {
    guard !functions.isEmpty else {
      return
    }

    for function in functions {
      let parameterList = function.parameters
        .map { "\($0.name): \($0.type.kotlinSpelling)" }
        .joined(separator: ", ")

      printer.print(
        "fun \(function.name)(\(parameterList)): \(function.resultType.kotlinSpelling) = TODO(\"Not implemented\")"
      )
    }
  }

  private func printSkippedDeclarations(_ printer: inout CodePrinter) {
    guard !skippedFunctions.isEmpty else {
      return
    }

    printer.print("")
    printer.print("// Skipped declarations:")
    for skipped in skippedFunctions {
      printer.print("// - \(skipped.swiftName): \(skipped.reason)")
    }
  }
}
