import Testing

@Suite
struct KotlinStubSourceTests {
  @Test("emits top-level stubs for the required subset")
  func emitsTopLevelStubs() throws {
    let output = try composeKotlinStubSource(
      """
      public func add(a: Int, b: Int32) -> Int { a + Int(b) }
      public func featureFlag() -> Bool { true }
      public func greet(name: String) -> String { name }
      public func ping() {}
      """
    )

    assertOutput(
      output,
      expected:
        """
        // Generated by jextract-swift
        // Swift module: SwiftModule
        package com.example.swift
        fun add(a: Int, b: Int): Int = TODO("Not implemented")
        fun featureFlag(): Boolean = TODO("Not implemented")
        fun greet(name: String): String = TODO("Not implemented")
        fun ping(): Unit = TODO("Not implemented")
        """
    )
  }
}
